Remove typeclass from interval constructor
twitter/algebird pull request #605
Opened 2016-12-11 22:42 UTC by sritchie

Moves the `Ordering` inputs from the constructor to the methods that need it, as discussed in #600 .

2016-12-12 01:19 UTC, johnynek requested changes

2016-12-12 01:19 UTC, johnynek commented on algebird-core/src/main/scala/com/twitter/algebird/Interval.scala
> +  def apply(t: T)(implicit ord: Ordering[T]) = contains(t)
Let's make apply and `&&` final

2016-12-12 01:19 UTC, johnynek commented on algebird-core/src/main/scala/com/twitter/algebird/Interval.scala
> +  def mapNonDecreasing[U](fn: T => U): Interval[U]
Think we need a test for mapNonDecreasing.

2016-12-12 01:19 UTC, johnynek commented on algebird-core/src/main/scala/com/twitter/algebird/Interval.scala
> +  def toLeftClosedRightOpen(implicit s: Successible[T]): Option[Intersection[InclusiveLower, ExclusiveUpper, T]] =
Let's try to see if we can just jump Successible and Predecessible up to Ordering. I can't think of a good reason to have Partial there.

2016-12-12 01:35 UTC, johnynek commented on algebird-core/src/main/scala/com/twitter/algebird/Interval.scala
> +  def mapNonDecreasing[U](fn: T => U): Interval[U]
So a law might be: forAll intervals and values t, if we map t and the interval, contains returns the same value.

To make the function non-decreasing we will need to do something like make a new fn and apple the first and if the result is less return the input.

2016-12-12 22:32 UTC, sritchie commented on algebird-core/src/main/scala/com/twitter/algebird/Interval.scala
> +  def toLeftClosedRightOpen(implicit s: Successible[T]): Option[Intersection[InclusiveLower, ExclusiveUpper, T]] =
it works great!

2016-12-12 23:53 UTC, oscar-stripe commented on algebird-core/src/main/scala/com/twitter/algebird/Interval.scala
> +  def leastToGreatest(implicit s: Successible[T], ord: Ordering[T]): Iterable[T] = {
don't need `ord` now that `Successible` has an Ordering right?

2016-12-12 23:54 UTC, sritchie commented on algebird-core/src/main/scala/com/twitter/algebird/Interval.scala
> +  def apply(t: T)(implicit ord: Ordering[T]) = contains(t)
done

2016-12-12 23:54 UTC, sritchie commented on algebird-core/src/main/scala/com/twitter/algebird/Interval.scala
> +  def mapNonDecreasing[U](fn: T => U): Interval[U]
done

2016-12-12 23:59 UTC, oscar-stripe requested changes

2016-12-12 23:59 UTC, oscar-stripe commented on algebird-core/src/main/scala/com/twitter/algebird/Interval.scala
> +  def greatestToLeast(implicit p: Predecessible[T], ord: Ordering[T]): Iterable[T] = {
we don't need `ord` here, right?

2016-12-12 23:59 UTC, oscar-stripe commented on algebird-core/src/main/scala/com/twitter/algebird/Predecessible.scala
> +   *   .map { n => ordering.lteq(n, t) && (!ordering.equiv(t, n)) }
this can be more succinct now: `prev(t).map(ordering.lt(_, t)).getOrElse(true)`

2016-12-12 23:59 UTC, oscar-stripe commented on algebird-core/src/main/scala/com/twitter/algebird/Successible.scala
> +   *   .map { n => ordering.lteq(t, n) && (!ordering.equiv(t, n)) }
similar: `next(t).map(ordering.lt(t, _)).getOrElse(true)`

2016-12-13 00:47 UTC, johnynek approved these changes

2016-12-13 00:47 UTC, merged